import { useNavigate } from "react-router-dom";
import { useAuth } from "@/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { Sparkles, ChevronRight, BookOpen, Target, Zap, Users } from "lucide-react";
import { useEffect } from "react";

const Index = () => {
  const { user, loading } = useAuth();
  const navigate = useNavigate();

  useEffect(() => {
    if (!loading && user) {
      navigate("/dashboard");
    }
  }, [user, loading, navigate]);

  return (
    <div className="min-h-screen relative overflow-hidden">
      {/* Background */}
      <div className="fixed inset-0 overflow-hidden pointer-events-none">
        <div className="absolute top-1/4 left-1/4 w-96 h-96 bg-primary/20 rounded-full blur-3xl animate-float" />
        <div className="absolute bottom-1/4 right-1/4 w-80 h-80 bg-accent/20 rounded-full blur-3xl animate-float" style={{ animationDelay: "2s" }} />
      </div>

      {/* Navbar */}
      <nav className="relative z-10 container mx-auto px-4 py-6 flex items-center justify-between">
        <div className="flex items-center gap-2">
          <div className="p-2 rounded-lg bg-gradient-to-br from-primary to-accent">
            <Sparkles className="w-5 h-5 text-primary-foreground" />
          </div>
          <span className="font-display font-bold text-xl gradient-text">StudyPath</span>
        </div>
        <div className="flex items-center gap-3">
          <Button variant="ghost" onClick={() => navigate("/auth")}>Sign In</Button>
          <Button variant="gradient" onClick={() => navigate("/auth")}>Get Started</Button>
        </div>
      </nav>

      {/* Hero */}
      <main className="relative z-10 container mx-auto px-4 pt-20 pb-32">
        <div className="max-w-4xl mx-auto text-center">
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-primary/10 text-primary text-sm mb-6 animate-slide-up">
            <Sparkles className="w-4 h-4" />
            AI-Powered Learning Platform
          </div>
          
          <h1 className="text-4xl md:text-6xl font-display font-bold text-foreground mb-6 animate-slide-up" style={{ animationDelay: "0.1s" }}>
            Master any subject with <span className="gradient-text">personalized roadmaps</span>
          </h1>
          
          <p className="text-xl text-muted-foreground mb-8 max-w-2xl mx-auto animate-slide-up" style={{ animationDelay: "0.2s" }}>
            Whether you're preparing for competitive exams, college, job interviews, or certifications — StudyPath creates AI-powered study plans tailored to your goals.
          </p>

          <div className="flex flex-col sm:flex-row gap-4 justify-center animate-slide-up" style={{ animationDelay: "0.3s" }}>
            <Button variant="gradient" size="xl" onClick={() => navigate("/auth")} className="gap-2">
              Start Learning Free <ChevronRight className="w-5 h-5" />
            </Button>
          </div>
        </div>

        {/* Features */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mt-24 max-w-5xl mx-auto">
          {[
            { icon: Target, title: "AI Roadmaps", desc: "Get personalized study plans generated by AI based on your goals" },
            { icon: BookOpen, title: "Topic Tracking", desc: "Track progress at granular topic level across multiple roadmaps" },
            { icon: Zap, title: "Smart Quizzes", desc: "Test your knowledge with AI-generated quizzes and flashcards" },
          ].map((feature, i) => (
            <div key={i} className="glass-card p-6 text-center animate-slide-up" style={{ animationDelay: `${0.4 + i * 0.1}s` }}>
              <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-primary to-accent flex items-center justify-center mx-auto mb-4">
                <feature.icon className="w-6 h-6 text-primary-foreground" />
              </div>
              <h3 className="font-display font-semibold text-foreground mb-2">{feature.title}</h3>
              <p className="text-sm text-muted-foreground">{feature.desc}</p>
            </div>
          ))}
        </div>
      </main>
    </div>
  );
};

export default Index;
